# Generated by Django 5.2.1 on 2025-05-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_completed_booking',
        ),
    ]
